SRCS	=	main.c\
			../libft/ft_bzero.c\
			../libft/ft_putchar_fd.c\
			../libft/ft_putnbr_fd.c\
			../libft/ft_putstr_fd.c\
			../libft/ft_strjoin.c\
			../libft/ft_strlen.c\
			../libft/ft_itoa.c\
			../libft/ft_strlcpy.c\
			../libft/ft_substr.c\
			../libft/ft_memset.c\
			../ft_printf.c\
			../print_c.c\
			../print_d.c\
			../print_p.c\
			../print_s.c\
			../print_u.c\
			../print_x.c\
			../padding.c\
			../libft/ft_atoi.c\
			../spec_handler.c
OBJ		=	$(SRCS:.c=.o)

all:		$(SRCS)
			gcc $^ -o test